### ISSUE TITLE
Build file: antora-playbook.yml

### ISSUE THREAD

**Issue by szterretje** [szterretje/docs_trial#1]
```
site:
  title: Demo Documentation Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://demo-doc-site.org
  start_page: usermanual::index.adoc
content:
  sources:
  - url: https://github.com/szterretje/asciidoc_trial.git
    branches: HEAD
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '_'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
antora:
  extensions:
  - require: '@antora/lunr-extension'
```
